export const GET_EXERCISE_TYPES = 'GET_EXERCISE_TYPES';
export const GET_PROGRAMS = 'GET_PROGRAMS';
export const SET_CURRENT_EXERCISE = 'SET_CURRENT_EXERCISE';
export const SET_CURRENT_PROGRAM_ID = 'SET_CURRENT_PROGRAM_ID';
export const SET_CURRENT_DAY = 'SET_CURRENT_DAY';
export const SET_CURRENT_APPROACHES = 'SET_CURRENT_APPROACHES';

